### ISSUE TITLE
Motivation for documentation

### ISSUE THREAD

**Issue by davidwilby** [RSE-Sheffield/software_engineering_best_practices#9]
Could just be covered verbally, but I think there is good, research-relevant motivation for testing and licensing but there is perhaps some missing motivation for "why should I, as a researcher, write docstrings?"

**Comment by bobturneruk** [comment]
Agreed. I suggest we have some slides to introduce this.

**Comment by bobturneruk** [comment]
https://merely-useful.tech/py-rse/documentation.html
